"""adding geographical names

Revision ID: 235eee44e954
Revises: 578280956c02
Create Date: 2023-04-30 01:12:46.472727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql as ps
from geoalchemy2.types import Geometry


# revision identifiers, used by Alembic.
revision = "235eee44e954"
down_revision = "578280956c02"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "geographical_names",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("govt_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("name_lower", sa.String(), nullable=False),
        sa.Column("generic_category", sa.String(), nullable=False),
        sa.Column("generic_term", sa.String(), nullable=False),
        sa.Column("county", sa.String(), nullable=True),
        sa.Column(
            "state_province",
            ps.ENUM(name="campsitestateenum", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "country",
            ps.ENUM(name="campsitecountryenum", create_type=False),
            nullable=False,
        ),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column(
            "geo",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=False,
        ),
        sa.Column("priority_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("geographical_names")
    # ### end Alembic commands ###
